/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ace_obo_OBOJni */

#ifndef _Included_com_example_ace_obo_OBOJni
#define _Included_com_example_ace_obo_OBOJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ace_obo_OBOJni
 * Method:    getSession
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ace_obo_OBOJni_getSession
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ace_obo_OBOJni
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_ace_obo_OBOJni_Login
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_example_ace_obo_OBOJni
 * Method:    Reg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_ace_obo_OBOJni_Reg
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_example_ace_obo_OBOJni
 * Method:    testLibcurl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ace_obo_OBOJni_testLibcurl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
